repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^data_platform/src/|^utils/(survey_metadata_management|qc_bridge_nps_table)\.py$
      - id: end-of-file-fixer
        exclude: ^data_platform/src/|^utils/(survey_metadata_management|qc_bridge_nps_table)\.py$
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=500"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args: [--config=.flake8]
        files: ^(data_platform/src/|utils/)

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [--check, --line-length=120]
        exclude: ^data_platform/src/|^utils/(survey_metadata_management|qc_bridge_nps_table)\.py$

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--check, --profile=black, --line-length=120]
        exclude: ^data_platform/src/|^utils/(survey_metadata_management|qc_bridge_nps_table)\.py$
